stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - 'C:\"Program Files"\Unity\Hub\Editor\2020.1.4f1\Editor\Unity.exe -projectPath=C:\Users\User1\Desktop\Testing\temp-builds -runTests -testPlatform editmode -logFile -testResults -./unit-tests.xml'
